require('dotenv').config();
require('./config/database');

const Category = require('./models/category');
const Item = require('./models/item');

(async function() {
  await Category.deleteMany({});
  const categories = await Category.create([
    {name: 'Bags', sortOrder: 10},
    {name: 'Wallets', sortOrder: 20},
    {name: 'Accessories', sortOrder: 30},
    {name: 'Tech', sortOrder: 40},
    {name: 'Travel', sortOrder: 50},
  ]);

  await Item.deleteMany({});
  const items = await Item.create([
    {name: 'Market Tote', 
     description: 'This limited edition of our Market Tote features eye-catching embroidered patches from Bellroy ambassador and artist Karan Singh.',
     images: ['https://i.imgur.com/zf2TL5U.png', 'https://i.imgur.com/0GoRWTu.png'], 
     category: categories[0], price: 45.00},
     {name: 'Tokyo Totepack Compact', 
     description: 'This versatile chameleon adapts to your day, going from tote to backpack, in a scaled-down size with surprisingly sorted storage.',
     images: ['https://i.imgur.com/9F5Kv3m.png', 'https://i.imgur.com/aXSfbZj.png'], 
     category: categories[0], price: 175.00},
     {name: 'Melbourne Backpack', 
     description: 'This slim urban backpack features pared-down aesthetics and easy access, to keep modern professionals ready for business.',
     images: ['https://i.imgur.com/g3Nzf6l.png', 'https://i.imgur.com/apgQN4R.png'], 
     category: categories[0], price: 169.00},
     {name: 'Classic Backpack Compact', 
     description: 'This versatile all-rounder is built for weekends or work days, in a scaled-down size that holds what you need, without excess.',
     images: ['https://i.imgur.com/aBYu5tT.png', 'https://i.imgur.com/5qrgnyI.png'],
     category: categories[0], price: 149.00},
     {name: 'Global City Set', 
     description: 'The Coin Wallet makes handling change a breeze, and slips easily into the slim City Pouch, so you can explore new hoods like a local.',
     images: ['https://i.imgur.com/nklEhXd.png', 'https://i.imgur.com/1iMGTY0.png'], 
     category: categories[0], price: 129.00},
     {name: 'Classic Backpack Plus ', 
     description: 'Dual compartment carry in one streamlined backpack, for those who like a classic look with plenty of features.',
     images: ['https://i.imgur.com/ag3RYOk.png', 'https://i.imgur.com/d9Yl54a.png'], 
     category: categories[0], price: 189.00},
     {name: 'Tokyo Totepack', 
     description: 'This premium leather upgrade to our Tokyo Totepack adapts to your day, with two carry modes and surprisingly sorted storage.',
     images: ['https://i.imgur.com/P3at71e.png', 'https://i.imgur.com/jLUL2EQ.png'], 
     category: categories[0], price: 289.00},
     {name: 'Lite Duffel', 
     description: 'A traditional duffel with a twist, this bag is rugged enough for adventure, but light enough to let you move like the wind.',
     images: ['https://i.imgur.com/lD3obmR.png', 'https://i.imgur.com/ViTJihz.png'], 
     category: categories[0], price: 129.00},
     {name: 'Oslo Backpack', 
     description: 'A slim casual backpack for work or weekends, with storage for your laptop and accessories, and room for your everyday essentials.',
     images: ['https://i.imgur.com/FIzC7Wu.png', 'https://i.imgur.com/FIzC7Wu.png'], 
     category: categories[0], price: 169.00},
     {name: 'Travel Folio', 
     description: 'For peace of mind zipped up with your travel essentials. This compact travel folio holds two passports, eight cards and cash hidden in the back.',
     images: ['https://i.imgur.com/rdmHBT1.png', 'https://i.imgur.com/z1PCAxs.png'], 
     category: categories[1], price: 159.00},
     {name: 'Card Sleeve', 
     description: 'Our Card Sleeve is the perfect second wallet that allows you to carry overflow cards alongside your everyday wallet. Keep it in your bag or desk drawer and access those cards when you need.',
     images: ['https://i.imgur.com/arSQUzi.png', 'https://i.imgur.com/sh23zm3.png'], 
     category: categories[1], price: 55.00},
     {name: 'Slim Sleeve', 
     description: 'Chosen for Carryology’s best-in-class Essentials program, this slim billfold has been given custom material accents to suit.',
     images: ['https://i.imgur.com/EsfEQOg.png', 'https://i.imgur.com/y4EKtNT.png'], 
     category: categories[1], price: 79.00},
     {name: 'Slim Sleeve MIRUM® Edition', 
     description: 'This MIRUM® edition of our original slim design uses an innovative plant-based leather alternative with a premium look and feel.',
     images: ['https://i.imgur.com/9HGcnzk.png', 'https://i.imgur.com/RS23yyW.png'], 
     category: categories[1], price: 99.00},
     {name: 'Note Sleeve Premium Edition', 
     description: 'Balancing spacious and slim, this upgraded all-rounder’s innovative leather, and custom finishing details add to its refined look.',
     images: ['https://i.imgur.com/b1qIPi9.png', 'https://i.imgur.com/ep6xuJS.png'], 
     category: categories[1], price: 129.00},
     {name: 'Note Sleeve', 
     description: 'A traditional design with surprising storage, the Note Sleeve holds cards, bills and coins in a trim, professional billfold.',
     images: ['https://i.imgur.com/73FhGIw.png', 'https://i.imgur.com/ZjnEsJz.png'], 
     category: categories[1], price: 79.00},
     {name: 'Zip Wallet', 
     description: 'This upgraded classic features innovative leather, subtly contrasting textures and stitching details, for a refined look and feel.',
     images: ['https://i.imgur.com/XBRaBIW.png', 'https://i.imgur.com/wjnqs3X.png'], 
     category: categories[1], price: 119.00},
     {name: 'Note Sleeve', 
     description: 'A traditional design with surprising storage, the Note Sleeve holds cards, bills and coins in a trim, professional billfold.',
     images: ['https://i.imgur.com/xDLXOkl.png', 'https://i.imgur.com/sQxGc4x.png'],
     category: categories[1], price: 89.00},
     {name: 'Card Pocket', 
     description: 'This versatile little wallet unzips to reveal big flexible storage for cards, bills, coins and even a spare SIM.',
     images: ['https://i.imgur.com/UMTae96.png', 'https://i.imgur.com/e73kG4e.png'],  
     category: categories[1], price: 65.00},
     {name: 'Tech Kit Compact', 
     description: 'This little pouch organizes tech accessories in a big way, keeping your work day smooth and sorted wherever you are.',
     images: ['https://i.imgur.com/eT5Vx1F.png', 'https://i.imgur.com/ZwWyNi7.png'],  
     category: categories[4], price: 55.00},
     {name: 'Compact Digital Set', 
     description: 'The Laptop Sleeve and Tech Kit Compact keep your laptop and tech accessories secure, organized, and ready to slip into your bag.',
     images: ['https://i.imgur.com/EMDhVdf.png', 'https://i.imgur.com/3d1Y0ZE.png'],  
     category: categories[4], price: 89.00},
     {name: 'Toiletry Kit', 
     description: 'Groomed for everyday travel, the Toiletry Kit sorts your toiletries into a neat package that slides into your bag.',
     images: ['https://i.imgur.com/yM0xMrS.png', 'https://i.imgur.com/ZKIqzHn.png'],  
     category: categories[4], price: 55.00},
     {name: 'Toiletry Kit Plus', 
     description: 'This kit has big storage, intuitive organization and easy access, to keep your bathroom essentials sorted at home or away.',
     images: ['https://i.imgur.com/4Ct0pNH.png', 'https://i.imgur.com/Qxl9tlt.png'],  
     category: categories[4], price: 65.00},
     {name: 'Lite Duffel', 
     description: 'A traditional duffel with a twist, this bag is rugged enough for adventure, but light enough to let you move like the wind.',
     images: ['https://i.imgur.com/8YbwVPb.png', 'https://i.imgur.com/4ijZj2L.png'],  
     category: categories[4], price: 129.00},
     {name: 'Lite Sling', 
     description: 'Our lightest sling yet makes adventures feel weightless, while keeping your essentials right where you need them.',
     images: ['https://i.imgur.com/E5D8jQV.png', 'https://i.imgur.com/Rq4vR7H.png'],  
     category: categories[4], price: 85.00},
     {name: 'Tech Kit', 
     description: 'Artist and globetrotter Karan’s expressive finishes and customizable art patches bring extra life to this organized tech kit.',
     images: ['https://i.imgur.com/l85t9fz.png', 'https://i.imgur.com/NUCA0Rl.png'],  
     category: categories[4], price: 79.00},
     {name: 'Weekender Plus', 
     description: 'This spacious bag combines sleek styling with clever organization, so you can move smoothly and focus on the journey.',
     images: ['https://i.imgur.com/8PeRpLb.png', 'https://i.imgur.com/F7Ejo7j.png'],  
     category: categories[4], price: 299.00},
     {name: 'Venture Sling 6L', 
     description: 'A sling built for days around town or outdoor adventure, with a big focus on accessibility and easy organization.',
     images: ['https://i.imgur.com/YQVdBr6.png', 'https://i.imgur.com/702w4vn.png'],  
     category: categories[4], price: 125.00},
     {name: 'Leather Sleeve For AirTag', 
     description: 'This little sleeve gives your AirTag a premium leather touch, and keeps it securely fastened to your keys, bag or other accessories.',
     images: ['https://i.imgur.com/TvIJfNH.png', 'https://i.imgur.com/FiaVBMr.png'],  
     category: categories[2], price: 35.00},
     {name: 'Micro Pen', 
     description: 'Engage the ballpoint with a simple roll of your thumb, then fill in forms mid-flight. A supplied refill also keeps you in ink longer.',
     images: ['https://i.imgur.com/CfTLk44.png', 'https://i.imgur.com/llPQ0hs.png'],  
     category: categories[2], price: 25.00},
     {name: 'Key Cover Plus', 
     description: 'A magnetic closure helps the bifold design stay neatly together without resorting to bulky clips or latches. Easy enough to snap shut with one hand.',
     images: ['https://i.imgur.com/QivTKNz.png', 'https://i.imgur.com/slHIJyX.png'],  
     category: categories[2], price: 25.00},
     {name: 'Key Cover', 
     description: 'A magnetic closure helps the bifold design stay neatly together without resorting to bulky clips or latches. Easy enough to snap shut with one hand.',
     images: ['https://i.imgur.com/Cq9oNk7.png', 'https://i.imgur.com/nMX0d9m.png'],  
     category: categories[2], price: 49.00},
     {name: 'Key Case + Tool', 
     description: 'Unlock your world with the flick of a thumb, and get out of jams in a pinch, with the made-for-each-other Key Case and Key Tool.',
     images: ['https://i.imgur.com/YXPnwov.png', 'https://i.imgur.com/TMmiwGz.png'],  
     category: categories[2], price: 69.00},
     {name: 'Key Case', 
     description: 'Unlock your world with the flick of a thumb, and get out of jams in a pinch, with the made-for-each-other Key Case and Key Tool.',
     images: ['https://i.imgur.com/e2MmeU3.png', 'https://i.imgur.com/G8JjZzS.png'],  
     category: categories[2], price: 55.00},
     {name: 'Key Tool', 
     description: 'A durable hardshell key wrangler that lets you flick out your keys and open the door, all in a single twist.',
     images: ['https://i.imgur.com/sYLtHcn.png', 'https://i.imgur.com/cyWMUe3.png'],  
     category: categories[2], price: 19.00},
     {name: 'Pencil Case', 
     description: 'A sophisticated take on the pencil case, for pens, cables and so much more. Holds pens, pencils, cables and personal items.',
     images: ['https://i.imgur.com/HUs8ugl.png', 'https://i.imgur.com/8FXxBpa.png'],  
     category: categories[2], price: 39.00},
     {name: 'Tag Case', 
     description: 'This case keeps your AirTag secured and protected, in an impressively slim design with a smooth leather finish.',
     images: ['https://i.imgur.com/RA7u8Pe.png', 'https://i.imgur.com/0j65UnX.png'],  
     category: categories[2], price: 29.00},
     {name: 'Mod Phone Case', 
     description: 'This slim leather case protects your phone from the daily grind, and can be snapped to our Mod Wallet  Single Rail System.',
     images: ['https://i.imgur.com/wZa0ljy.png', 'https://i.imgur.com/r8eqz1x.png'],  
     category: categories[3], price: 59.00},
     {name: 'Mod Phone Case + Wallet', 
     description: 'This dynamic duo keeps your everyday cards securely snapped to your phone case, in super slim leather style.',
     images: ['https://i.imgur.com/53qLHNu.png', 'https://i.imgur.com/oEUrQIf.png'],  
     category: categories[3], price: 98.00},
     {name: 'Phone Case  3 Card', 
     description: '1 to 3 cards can be tucked behind the phone and accessible by flipping open the magnetic closure. It’s a clever microfiber-lined niche that keeps your cards safe but easily accessible, and your phone remains the main attraction. Like a magicians card-out-of-the-sleeve trick, but a little more everyday.',
     images: ['https://i.imgur.com/ZEGuhZO.png', 'https://i.imgur.com/kzW8dbx.png'],  
     category: categories[3], price: 79.00},
     {name: 'Mod Phone Case + Wallet', 
     description: 'This dynamic duo keeps your everyday cards securely snapped to your phone case, in super slim leather style',
     images: ['https://i.imgur.com/N1UebwM.png', 'https://i.imgur.com/YxiShW0.png'],  
     category: categories[3], price: 79.00},
     {name: 'Leather Case For Pixel', 
     description: 'This slim leather case, designed in partnership with Google, celebrates the premium look and feel of your Pixel 7 Pro.',
     images: ['https://i.imgur.com/3BJEDeA.png', 'https://i.imgur.com/tO4mtZY.png'],  
     category: categories[3], price: 55.00},
     {name: 'Phone Case For iPhone 12 Pro Max', 
     description: 'This slim case keeps your main card close at hand in a quick-draw sleeve, for easy swiping on the metro or at the shops.',
     images: ['https://i.imgur.com/d1t8Tmj.png', 'https://i.imgur.com/B7onQT8.png'],  
     category: categories[3], price: 29.00},
     {name: 'Pod Jacket Pro', 
     description: 'Give your AirPods a smooth leather touch, and some distinct personality, with this protective case.',
     images: ['https://i.imgur.com/bGxyzKN.png', 'https://i.imgur.com/oVPG6Kj.png'],  
     category: categories[3], price: 39.00},
     {name: 'Mod Battery Cover', 
     description: 'This slim cover gives your battery pack a premium leather look and feel, while keeping it securely snapped to your Mod Phone Case - Double Rail System.',
     images: ['https://i.imgur.com/hVulB86.png', 'https://i.imgur.com/zC40lAS.png'],  
     category: categories[3], price: 35.00},
     {name: 'Watch Strap', 
     description: 'From work to workouts, this sleek performance strap complements your Apple Watch, with sculpted curves and a smooth leather touch.',
     images: ['https://i.imgur.com/I03w6ci.png', 'https://i.imgur.com/GJl01Ig.png'],  
     category: categories[3], price: 69.00},



    
   
    
    
  
  ]);

  console.log(items)

  process.exit();

})();
